version: "3.7"

# FastAPI app
services:
  apis:
    build: ./apis
    container_name: apis
    ports:
      - 5000:5000
    networks: 
      ai-poc-network: 
        aliases: 
          - apis.docker

  orion-ld:
    image: fiware/orion-ld
    container_name: ai-orion-ld
    networks: 
      ai-poc-network: 
        aliases: 
          - ai.orion.docker
    expose:
      - "1028"
    ports:
      - "1028:1028"
    depends_on:
      - mongo-db
    command: -dbhost ai.mongo.docker -logLevel DEBUG -port 1028

  mongo-db:
    image: mongo:3.6
    container_name: ai-mongo-db
    ports:
      - "27018:27018" 
    networks: 
      ai-poc-network: 
        aliases: 
          - ai.mongo.docker
    command: --nojournal
    volumes:
      - ai-mongo-database:/ai-database#

  # @context file is served from here
  ngsi-ld-context:
    image: httpd:alpine
    container_name: ld-context
    hostname: context
    networks: 
      ai-poc-network: 
        aliases: 
          - context
    ports:
        - "3004:80"
    volumes:
        - ../data-models:/usr/local/apache2/htdocs/
    healthcheck:
      test: (wget --server-response --spider --quiet  http://context/ngsi-context.jsonld 2>&1 | awk 'NR==1{print $$2}'|  grep -q -e "200") || exit 1

networks:
  ai-poc-network:
    external: true
  
volumes:
  ai-mongo-database: ~
