version: "3.7"

# FastAPI app
services:
  apis:
    build: ./apis
    container_name: apis
    ports:
      - 5000:5000
    networks: 
      ai-poc-network: 
        aliases: 
          - apis.docker

  orion-ld:
    image: fiware/orion-ld
    container_name: ai-orion-ld
    networks: 
      ai-poc-network: 
        aliases: 
          - ai.orion.docker
    ports:
      - "1028:1026"
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:3.6
    container_name: ai-mongo-db
    ports:
      - "27018:27018" 
    networks: 
      ai-poc-network: 
        aliases: 
          - ai.mongo.docker
    command: --nojournal
    volumes:
      - ai-mongo-database:/ai-database#

  notification-proxy:
    image: quay.io/wi_stefan/notification-proxy
    container_name: notif-proxy
    ports:
      - 8080:8080
    environment:
      - MICRONAUT_SERVER_PORT=8080
      - GENERAL_TENANT=null
      - HTTP_SERVICES_BROKER_URL=http://localhost:1028

  # @context file is served from here
  ngsi-ld-context:
    image: httpd:alpine
    container_name: ld-context
    hostname: context
    networks: 
      ai-poc-network: 
        aliases: 
          - context
    ports:
        - "3004:80"
    volumes:
        - ../data-models:/usr/local/apache2/htdocs/
    healthcheck:
      test: (wget --server-response --spider --quiet  http://context/ngsi-context.jsonld 2>&1 | awk 'NR==1{print $$2}'|  grep -q -e "200") || exit 1

networks:
  ai-poc-network:
    name: ai-poc-network
  
volumes:
  ai-mongo-database: ~
